# Pipeline corregido con versiones válidas de GitHub Actions
name: Build and deploy JAR app to Azure Web App - Development

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository -Dfile.encoding=UTF-8'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -Dfile.encoding=UTF-8

      - name: Rename JAR file for Azure
        run: mv target/*.jar target/app.jar

      - name: Verify JAR file
        run: |
          if [ ! -f target/app.jar ]; then
            echo "JAR file not found!"
            exit 1
          fi
          if [ ! -s target/app.jar ]; then
            echo "JAR file is empty!"
            exit 1
          fi
          echo "JAR file size: $(ls -lh target/app.jar)"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app-dev
          path: '${{ github.workspace }}/target/app.jar'

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-dev

      - name: Verify downloaded artifact
        run: |
          if [ ! -f app.jar ]; then
            echo "Downloaded JAR file not found!"
            exit 1
          fi
          echo "Ready to deploy: $(ls -lh app.jar)"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 2525798b-9ac2-48ed-8da2-947cc330567c
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4552960A0044FECAB62BE95596F7E6F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86C4C80481F64E818FF15CCBC8C80734 }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ForoEscolarTest'  # Verifica que este sea el nombre correcto
          slot-name: 'Production'
          package: '*.jar'

      - name: Logout from Azure
        run: az logout